joint1_position:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 100, i: 0, d: 1}

joint2_position:
  type: position_controllers/JointPositionController
  joint: joint2
  pid: {p: 100, i: 0, d: 1}

joint3_position:
  type: position_controllers/JointPositionController
  joint: joint3
  pid: {p: 100, i: 0, d: 1}

joint4_position:
  type: position_controllers/JointPositionController
  joint: joint4
  pid: {p: 100, i: 0, d: 1}
